### ISSUE TITLE
use regenerator due to generator.return

### ISSUE THREAD

**Issue by bmeck** [jbach/babel-preset-es2015-node4#1]
v8 in node v4 does not implement generator.return, it should according to es2015. for now, I would recommend using regenerator in case any codeuses `.return`. This is usually task runners like: galaxy, generator-runner, etc. , but anything using them would need it as well.

**Comment by jbach** [comment]
Thanks. It’s a shame, but you’re right. I guess node@5 doesn’t support generator.return either, does it?

**Comment by bmeck** [comment]
latest v8 is still working on landing it

**Comment by jbach** [comment]
That makes it a bug in https://github.com/alekseykulikov/babel-preset-es2015-node5 too

**Comment by Pana** [comment]
Got it
