### ISSUE TITLE
missing transform-es2015-function-name

### ISSUE THREAD

**Issue by hax** [jbach/babel-preset-es2015-node4#3]
And not need transform-es2015-typeof-symbol.

You could use https://github.com/hax/babel-features/tree/2.x to get the feature list. (currently you need to clone the repo and run `node test` to get the list, I will update it soon to add command to generate preset file.)

**Comment by jbach** [comment]
The [compatibility table](https://kangax.github.io/compat-table/es6/) shows 9/17 for babel and 6/17 for Node. How do we determine, whether the inclusion of a plugin makes sense? It’s the same discussion as #1, #2 and https://github.com/alekseykulikov/babel-preset-es2015-node5/issues/3.

I’m kinda torn on this one, I guess, but I’m leaning towards keeping the presets barebones (thus removing regenerator again) and leaving it up to the user to include "grey-area" plugins like regenerator or function-name (which is also what @alekseykulikov described [here](https://github.com/alekseykulikov/babel-preset-es2015-node5/issues/3#issuecomment-155835670)).

Correct me if I’m wrong, but babel-features tests just the features that babel provides, so what if native implements features that babel doesn’t (as is the case with bound functions name)?

As for typeof-symbol, it will be removed (see #2).

**Comment by hax** [comment]
The `es2015-function-name` transformer will not break the engines, but patch the function names which can be determined statically, and may pass more tests (11/17) with Node env. So we should use it.

This feature is not like generators, because regenerate will transform the generators to a very different code which can not utilize engine's generators implementation. This is why my project also report `transform-regenerator` is required.

**Comment by jbach** [comment]
Okay, I guess my main qualm with adding plugins is that babel@6 removed the blacklist option. So users may always add regenerator manually but may not remove it if it set via presets. @bmeck, what’s your take on that? Would it warrant remove regenerator again?

**Comment by hax** [comment]
@jbach Yes, I also think missing `blacklist` option is somewhat inconvenient. Maybe we should rasie an issue in babel project.
