### ISSUE TITLE
Feature request : Loose mode

### ISSUE THREAD

**Issue by yvele** [jbach/babel-preset-es2015-node4#7]
It would be awesome if we could pass options such as [loose mode](https://developit.github.io/babel-legacy-docs/docs/advanced/loose/)

You can eventually have a look at [how es2015-node6 manages options](https://github.com/jhen0409/babel-preset-es2015-node6)
...but do not fall into [this issue](https://github.com/jhen0409/babel-preset-es2015-node6/issues/7) :stuck_out_tongue_closed_eyes: 

PS: Then I will be able to depreciate [babel-preset-es2015-node4-loose](https://github.com/yvele/babel-preset-es2015-node4-loose)

**Comment by hzoo** [comment]
Would you be cool with deprecating this in favor of https://github.com/babel/babel-preset-env? It covers node 4 as well and also this request for loose mode. Was thinking it could replace all of the es20xx-nodex, etc presets and so we can all work on a single preset that everyone can use + make better. Thanks for considering! (also just FYI I'm maintaining Babel + the preset atm)

**Comment by jbach** [comment]
@hzoo, good thinking! I deprecated the package.
